### PR TITLE
feat: add migration from file. closes #7

### LINKED ISSUE #7: Implement the migrationFromFile service
The service will receive a JSON filePath, validate if the schema is ok and insert the data from this file in the local database.

Just as a starting point, I created the package `migration` with the function `migrateFromURL` and `migrateFromFile`. The ideia is that when this issue is ready, the `migrateFromURL` with be as easy as downloading the file and invoking this function. But that's **not** on the scope here. We will tie all of this when the #6 is ready too.

How about this?

### PR DESCRIPTION
**Pull request by eniovalo**
Hi @tiagostutz and @zamariola ,
Could you verify if this PR (closes #7 ) is OK? :slightly_smiling_face: 

I add the migration from json file.

Obs: I create *test-migration.json* at testdata because in this [article](https://medium.com/rungo/unit-testing-made-easy-in-go-25077669318) they say that it will be ignored on build.

Below is some images of the execution:
console text:
Captura de tela de 2020-07-22 16-32-22

Database - Item:
Captura de tela de 2020-07-22 16-30-59

Database - Tag:
Captura de tela de 2020-07-22 16-31-23

Database - Item x Tag:
Captura de tela de 2020-07-22 16-32-00

Thanks.

### CODE REVIEW

**Comment by tiagostutz** [comment]
Hi there @GreenStage and @zamariola could you please take a look at this PR? I gave you both write access to the repo so if you wish to make directly contributions to @eniovalo's  [branch](https://github.com/eniovalo/stop-analyzing-api/tree/issue-7-migrationFromFile), you are able to. You just clone his fork, checkout the branch, do your stuff and push.

If you don't have time for that, let me know and I'm assigning the review for me.
Thanks! =)

**Comment by zamariola** [comment]
It's ok for me. I think we can merge as-is.
If I had to suggest something, it'd be an integration test.  Considering that we are importing a file, we can use Golden files:

https://ieftimov.com/post/testing-in-go-golden-files/

Thanks!

**Comment by tiagostutz** [comment]
> It's ok for me. I think we can merge as-is.
> If I had to suggest something, it'd be an integration test. Considering that we are importing a file, we can use Golden files:
> 
> https://ieftimov.com/post/testing-in-go-golden-files/
> 
> Thanks!

Great point. Could you open an issue for that? I think that would be a good issue for beginners. Agree?

**Comment by eniovalo** [comment]
> It's ok for me. I think we can merge as-is.
> If I had to suggest something, it'd be an integration test. Considering that we are importing a file, we can use Golden files:
> 
> https://ieftimov.com/post/testing-in-go-golden-files/
> 
> Thanks!

Hi @zamariola ,
Really interesting this article about golden files. 🙂 

Thanks.

**Comment by zamariola** [comment]
The issue has been created: https://github.com/bancodobrasil/stop-analyzing-api/issues/20

**Pull request merged**
